version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./logs/php:/var/log
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty123
      MYSQL_DATABASE: first_db
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
